version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16-stretch

    working_directory: ~/repo
    branches:
      only: master

    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ac:ac:31:d0:a6:dc:8d:0d:7d:51:3d:80:1d:dd:cb:df'

      - checkout

      # Using cached node_modules sometimes caused weird behavior with outdated dependencies even
      # if a newer version was present in package.json so saving an restoring dependencies is
      # commented out. Should be investigated.

      # Download and cache dependencies
      # - restore_cache:
      #       keys:
      #           - v1-dependencies-{{ checksum "package.json" }}
      #           # fallback to using the latest cache if no exact match is found
      #           - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn --pure-lockfile

      # - save_cache:
      #       paths:
      #           - node_modules
      #       key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Library
          command: yarn build

      - run:
          name: Release
          command: yarn release

      - run:
          name: Build Storybook
          command: yarn storybook:build

      - deploy:
          name: Deploy Storybook
          command: yarn storybook:deploy
