import React from 'react';
import { storiesOf } from '@storybook/react';
import Hierarchy from '../../.storybook/hierarchyGroups';
// import { Card } from '..';
import { Grid, Row, Column } from '.';
import css from './Grid.module.css';

storiesOf(`${Hierarchy.LAYOUT}|Grid`, module)
    .addWithJSX('Fixed max width', () => (
        <Grid>
            <Row className={css.debug}>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    1
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    2
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    3
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    4
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    5
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    6
                </Column>
            </Row>
        </Grid>
    ))
    .addWithJSX('Fluid width', () => (
        <Grid fluid>
            <Row className={css.debug}>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    1
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    2
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    3
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    4
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    5
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    6
                </Column>
            </Row>
        </Grid>
    ))
    .addWithJSX('Aligned columns', () => (
        <Grid>
            <Row
                className={css.debug}
                textAlign="right"
                justifyContent="center"
            >
                <Column xs={4} className={css.debug}>
                    Centered column
                </Column>
            </Row>
        </Grid>
    ))
    .addWithJSX('12 units with fixed width', () => (
        <Grid>
            <Row className={css.debug}>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    1
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    2
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    3
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    4
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    5
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    6
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    7
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    8
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    9
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    10
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    11
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={4}
                    lg={3}
                    xl={2}
                    className={css.debug}
                >
                    12
                </Column>
            </Row>
        </Grid>
    ))
    .addWithJSX('Nested grid', () => (
        <Grid>
            <Row>
                <Column
                    xs={12}
                    sm={6}
                    md={5}
                    lg={4}
                    xl={3}
                    className={css.debug}
                >
                    1
                </Column>
                <Column
                    xs={12}
                    sm={6}
                    md={7}
                    lg={8}
                    xl={9}
                    className={css.debug}
                >
                    <Grid>
                        <Row className={css.debug}>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                1
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                2
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                3
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                4
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                5
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                6
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                7
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                8
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                9
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                10
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                11
                            </Column>
                            <Column
                                xs={12}
                                md={3}
                                lg={2}
                                xl={1}
                                className={css.debug}
                            >
                                12
                            </Column>
                        </Row>
                    </Grid>
                </Column>
            </Row>
        </Grid>
    ));
