export default [
    'typescript-icon.svg',
    'javascript.svg',
    'html-5.svg',
    'css-3.svg',
    'react.svg',
    'redux.svg',
    'nextjs.svg',
    'expo.svg',
    'nodejs.svg',
    'deno.svg',
    'webpack.svg',
    'vitejs.svg',
    'esbuild.svg',
    'babel.svg',
    'npm.svg',
    'yarn.svg',
    'express.svg',
    'prettier.svg',
    'react-router.svg',
    // 'flow.svg',
    'jest.svg',
    'storybook-icon.svg',
    'immutable.svg',
    'gatsby.svg',
    'react-query-icon.svg',
    'gulp.svg',
    'grunt.svg',
    'pm2.svg',
    'nginx.svg',
    'sass.svg',
    'postcss.svg',
    'github-octocat.svg',
    'gitlab.svg',
    'git-icon.svg',
    'chrome.svg',
    // 'firefox.svg',
    // 'microsoft-edge.svg',
    // 'internetexplorer.svg',
    // 'opera.svg',
    // 'safari.svg',
    'mysql.svg',
    'mariadb.svg',
    'mongodb.svg',
    'snyk.svg',
    'supabase-icon.svg',
    'bootstrap.svg',
    // 'foundation.svg',
    // 'polymer.svg',
    'webcomponents.svg',
    'backbone-icon.svg',
    'ember-tomster.svg',
    'handlebars.svg',
    // 'socket.io.svg',
    'visual-studio-code.svg',
    // 'atom.svg',
    'php.svg',
    'digital-ocean.svg',
    'aws.svg',
    'apache.svg',
    'circleci.svg',
    // 'strider.svg',
    'docker.svg',
    'vagrant.svg',
];
